Repository OZ-Coding-School/oz_03_collabo-004-FE, pull requests merged in 2024-08, with the labels that each got.

#1 Common 컴포넌트 작업
  .github/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
  public/img/header_logo.png
  public/img/profile_placeholder.png
  src/common/badge/Badge.tsx
  src/common/badge/BadgeTopic.tsx
  src/common/button/Button.tsx
  src/common/button/ButtonLogin.tsx
  src/common/header/Header.tsx
  src/common/header/HeaderInfo.tsx
  src/common/header/HeaderInfoLogged.tsx
  src/common/header/HeaderSearch.tsx
  src/common/profile/ProfileImage.tsx
  src/common/profile/ProfileStatus.tsx
  src/common/toast/Toast.tsx
  src/config/store.tsx
  src/global.css
  src/pages/PageComponent.tsx
  tailwind.config.js
Labels: Feat

#2 Feat: WriteModal 컴포넌트 작성완료
  src/common/writeModal/WriteModal.tsx
Labels: Feat

#3 공통 컴포넌트 작업 (전문태그, 마이페이지 info)
  src/common/info/InfoMyPageLeft.tsx
  src/common/info/InfoMyPageRight.tsx
  src/common/tag/TagSkill.tsx
  src/pages/PageComponent.tsx
Labels: Feat

#5 BadgeResister 컴포넌트 생성
  src/common/badge/BadgeResister.tsx
Labels: Feat

#7 공통 컴포넌트 작업
  src/common/comment/CommentMyPage.tsx
  src/common/content/ContentMyPage.tsx
  src/common/info/InfoMyPageLeft.tsx
  src/common/info/InfoMyPageRight.tsx
  src/common/skeleton/Skeleton.tsx
  src/common/skeleton/SkeletonContent.tsx
  src/common/skeleton/SkeletonTrendingComment.tsx
  src/common/skeleton/SkeletonTrendingContent.tsx
  src/common/tag/TagSkill.tsx
  src/config/const.tsx
  src/pages/PageComponent.tsx
Labels: Feat, Design, Remove

#10 Favicon 추가
  index.html
  public/favicon/android-chrome-192x192.png
  public/favicon/apple-touch-icon.png
  public/favicon/browserconfig.xml
  public/favicon/favicon-16x16.png
  public/favicon/favicon-32x32.png
  public/favicon/favicon.ico
  public/favicon/mstile-150x150.png
  public/favicon/safari-pinned-tab.svg
  public/favicon/site.webmanifest
Labels: Feat

#11 Comment 컴포넌트 작성
  src/common/comment/Comment.tsx
Labels: Feat

#12 태그 3개 선택시 제한 및 컴포넌트 css 수정
  src/common/content/ContentFooter.tsx
  src/common/info/InfoMyPageLeft.tsx
  src/common/info/InfoMyPageRight.tsx
  src/common/skeleton/SkeletonContent.tsx
  src/common/skeleton/SkeletonTrendingComment.tsx
  src/common/skeleton/SkeletonTrendingContent.tsx
  src/common/tag/TagSkill.tsx
  src/common/topic/Topic.tsx
  src/common/trending/TrendingComment.tsx
  src/common/trending/TrendingContent.tsx
  src/config/const.tsx
  src/pages/PageComponent.tsx
Labels: Feat, Design

#14 서버 프록시 수정
  src/api/auth.ts
  src/api/index.ts
  src/main.tsx
  src/pages/PageComponent.tsx
  vite.config.ts
Labels: Test

#15 인증 로직 재수정, BE 개발 완료시 테스트 필요
  src/AdminRoute.tsx
  src/App.tsx
  src/PrivateRoute.tsx
  src/hooks/useVerify.tsx
  src/routes/AdminRoute.tsx
  src/routes/PrivateRoute.tsx
  vite.config.ts.timestamp-1724412567120-bbaba9dd369f9.mjs
Labels: Test

#16 마이페이지 컴포넌트 합치기 + api 추가
  src/api/account.ts
  src/api/index.ts
  src/common/content/ContentMyPage.tsx
  src/common/info/InfoMyPageLeft.tsx
  src/common/info/InfoMyPageRight.tsx
  src/common/modal/ModalDetail.tsx
  src/common/tag/TagSkill.tsx
  src/global.css
  src/pages/MyPage.tsx
Labels: Feat, Design

#19 사용자 로그인 초기데이터 INIT 추가
  public/favicon/site.webmanifest
  src/config/store.tsx
  src/config/types.ts
  src/pages/HomePage.tsx
Labels: Feat

#20 Feat: https 백엔드 도메인 도입
  src/api/auth.ts
  src/pages/HomePage.tsx
  vite.config.ts
Labels: Feat

#24 Admin Auth 페이지 초안 작성 및 기본API 연동 작업
  package-lock.json
  package.json
  src/admin/AdminUserList.tsx
  src/api/admin.ts
  src/api/auth.ts
  src/api/index.ts
  src/common/header/Header.tsx
  src/lib/utils.ts
  src/pages/AdminPage.tsx
  src/routes/AdminRoute.tsx
Labels: Feat

#22 로그인, 회원가입, 태그 선택 페이지 작업
  package-lock.json
  package.json
  public/img/hunsu_logo_dark.png
  src/App.tsx
  src/pages/LoginPage.tsx
  src/pages/RegisterPage.tsx
  src/pages/TagPage.tsx
Labels: Design
