Repository OZ-Coding-School/oz_03_collabo-004-FE, pull requests merged in 2024-09, with the labels that each got.

#27 Dev/home
  src/api/article.ts
  src/common/content/Content.tsx
  src/common/content/ContentFooter.tsx
  src/common/modal/ModalEditor.tsx
  src/common/profile/ProfileImage.tsx
  src/common/topic/Topic.tsx
  src/config/types.ts
  src/pages/HomePage.tsx
Labels: Refactor

#25 마이페이지, 디테일 모달 작업
  src/App.tsx
  src/api/ai.ts
  src/api/comment.ts
  src/common/comment/Comment.tsx
  src/common/comment/CommentInput.tsx
  src/common/content/ContentMyPage.tsx
  src/common/info/InfoMyPageLeft.tsx
  src/common/info/InfoMyPageRight.tsx
  src/common/modal/ModalDetail.tsx
  src/common/modal/ModalPicture.tsx
  src/common/profile/ProfileStatus.tsx
  src/common/tab/TabItem.tsx
  src/config/const.tsx
  src/config/store.tsx
  src/config/types.ts
  src/hooks/useLevelTitle.tsx
  src/pages/HomePage.tsx
  src/pages/MyPage.tsx
Labels: Feat, Design, Style

#26 로그인, 회원가입, 태그 선택 페이지
  src/api/auth.ts
  src/common/button/Button.tsx
  src/common/tag/TagSkill.tsx
  src/config/types.ts
  src/pages/LoginPage.tsx
  src/pages/RegisterPage.tsx
  src/pages/TagPage.tsx
Labels: Feat, Design

#28 dev/main 병합후 문제사항 수정, 로그인 로그아웃 모달 연동
  eslint.config.js
  src/App.tsx
  src/common/header/Header.tsx
  src/common/header/HeaderInfo.tsx
  src/common/header/HeaderInfoLogged.tsx
  src/common/modal/ModalLogin.tsx
  src/common/modal/ModalRegister.tsx
  src/common/profile/ProfileImage.tsx
  src/common/profile/ProfileStatus.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/RegisterPage.tsx
  src/routes/PublicRoute.tsx
Labels: Feat, Fix

#29 로그인, 게시글 연동과정 수정
  src/api/index.ts
  src/common/header/Header.tsx
  src/common/header/HeaderInfo.tsx
  src/common/info/InfoMyPageLeft.tsx
  src/common/input/EditorInput.tsx
  src/common/modal/ModalEditor.tsx
  src/common/profile/ProfileImage.tsx
  src/common/profile/ProfileStatus.tsx
  src/config/store.tsx
  src/config/types.ts
  src/pages/HomePage.tsx
  src/pages/MyPage.tsx
Labels: Fix

#30 HomePage 코드 일부 수정
  src/common/content/ContentFooter.tsx
  src/common/topic/Topic.tsx
  src/common/trending/TrendingComment.tsx
  src/common/trending/TrendingContent.tsx
  src/pages/HomePage.tsx
Labels: Refactor

#31 디테일 모달 작업
  src/api/account.ts
  src/api/comment.ts
  src/common/badge/BadgeDesc.tsx
  src/common/comment/Comment.tsx
  src/common/comment/CommentInput.tsx
  src/common/content/ContentMyPage.tsx
  src/common/info/InfoMyPageLeft.tsx
  src/common/modal/ModalDetail.tsx
  src/common/profile/ProfileImage.tsx
  src/common/profile/ProfileStatus.tsx
  src/config/store.tsx
  src/config/types.ts
  src/hooks/useFormatDate.tsx
  src/pages/MyPage.tsx
Labels: Feat, Fix, Design

#32 홈페이지에 디테일 모달 연결
  src/api/report.ts
  src/common/comment/Comment.tsx
  src/common/info/InfoMyPageLeft.tsx
  src/common/modal/ModalReport.tsx
  src/config/types.ts
  src/pages/HomePage.tsx
Labels: Feat

#33 로그인/회원가입, 마이페이지, 디테일 모달 작업
  package.json
  src/common/button/ButtonLogin.tsx
  src/common/comment/Comment.tsx
  src/common/comment/CommentInput.tsx
  src/common/content/ContentMyPage.tsx
  src/common/modal/ModalDetail.tsx
  src/common/modal/ModalReport.tsx
  src/pages/LoginPage.tsx
  src/pages/RegisterPage.tsx
Labels: Fix, Design

#37 Test: 백엔드 서버 통신 문제 테스트
  src/App.tsx
  src/common/comment/CommentInput.tsx
  src/common/content/ContentMyPage.tsx
  src/common/header/Header.tsx
  src/common/header/HeaderSearch.tsx
  src/common/modal/ModalDetail.tsx
  src/common/modal/ModalEditor.tsx
  src/common/modal/ModalLogin.tsx
  src/common/modal/ModalPicture.tsx
  src/common/modal/ModalRegister.tsx
  src/common/trending/TrendingComment.tsx
  src/common/trending/TrendingContent.tsx
  src/config/store.tsx
  src/pages/HomePage.tsx
  vite.config.ts
Labels: Test

#38 Test: CORS 테스트
  src/api/axios.ts
Labels: Test

#39 Test: CORS 테스트
  vite.config.ts
Labels: Test

#40 Test: CORS 테스트
  src/api/axios.ts
Labels: Test

#41 Test: CORS 테스트
  src/api/axios.ts
  vite.config.ts
Labels: Test

#42 Test: CORS 테스트
  src/api/axios.ts
  vite.config.ts
Labels: Test

#43 Design: css 수정 및 axios 수정
  src/api/axios.ts
  src/common/comment/Comment.tsx
  src/common/comment/CommentInput.tsx
  src/common/content/ContentMyPage.tsx
  src/common/info/InfoMyPageRight.tsx
  src/common/modal/ModalDetail.tsx
  src/common/modal/ModalPicture.tsx
  src/common/modal/ModalReport.tsx
  src/common/topic/Topic.tsx
  src/common/trending/TrendingComment.tsx
  src/common/trending/TrendingContent.tsx
  src/pages/HomePage.tsx
  src/pages/MyPage.tsx
  src/pages/TagPage.tsx
Labels: Design

#44 Test: 쿠키 문제 확인
  src/api/axios.ts
  src/common/comment/Comment.tsx
  src/common/comment/CommentInput.tsx
  src/common/content/ContentMyPage.tsx
  src/common/info/InfoMyPageRight.tsx
  src/common/modal/ModalDetail.tsx
  src/common/modal/ModalPicture.tsx
  src/common/modal/ModalReport.tsx
  src/common/topic/Topic.tsx
  src/common/trending/TrendingComment.tsx
  src/common/trending/TrendingContent.tsx
  src/pages/HomePage.tsx
  src/pages/MyPage.tsx
  src/pages/TagPage.tsx
Labels: Test

#46 알림 기능 추가
  src/api/index.ts
  src/api/notification.ts
  src/common/header/HeaderInfoLogged.tsx
  src/common/info/InfoMyPageRight.tsx
  src/config/types.ts
  src/pages/RegisterPage.tsx
Labels: Feat, Fix, Design

#47 배포환경 동작 확인
  src/api/article.ts
  src/api/axios.ts
  src/api/index.ts
  src/api/notification.ts
  src/common/content/Content.tsx
  src/common/editor/Editor.tsx
  src/common/header/HeaderInfoLogged.tsx
  src/common/info/InfoMyPageRight.tsx
  src/common/modal/ModalEditor.tsx
  src/common/modal/ModalEditorSelect.tsx
  src/common/profile/ProfileStatus.tsx
  src/config/store.tsx
  src/config/types.ts
  src/pages/HomePage.tsx
  src/pages/RegisterPage.tsx
  tailwind.config.js
  vite.config.ts
Labels: Test

#48 게시글 신고 기능 작업
  src/api/report.ts
  src/common/comment/Comment.tsx
  src/common/header/HeaderInfoLogged.tsx
  src/common/modal/ModalDetail.tsx
  src/common/modal/ModalReport.tsx
Labels: Feat, Design

#49 배포환경 작동 테스트
  src/api/article.ts
  src/api/axios.ts
  src/api/report.ts
  src/common/comment/Comment.tsx
  src/common/content/ContentMyPage.tsx
  src/common/editor/Editor.tsx
  src/common/header/Header.tsx
  src/common/header/HeaderInfoLogged.tsx
  src/common/header/HeaderSearch.tsx
  src/common/input/EditorInput.tsx
  src/common/modal/ModalConfirm.tsx
  src/common/modal/ModalDelete.tsx
  src/common/modal/ModalDetail.tsx
  src/common/modal/ModalEditor.tsx
  src/common/modal/ModalReport.tsx
  src/config/types.ts
  src/pages/AdminPage.tsx
  src/pages/HomePage.tsx
  vite.config.ts
Labels: Test

#50 배포환경 작동 테스트
  src/common/modal/ModalDetail.tsx
  src/config/types.ts
Labels: Test

#52 에디터 공백 작성시 발생하는 문제 수정
  src/common/editor/Editor.tsx
Labels: Fix

#53 알림 신고기능 추가
  src/common/comment/Comment.tsx
  src/common/header/HeaderInfo.tsx
  src/common/header/HeaderInfoLogged.tsx
  src/common/modal/ModalDetail.tsx
  src/common/topic/Topic.tsx
  src/pages/HomePage.tsx
Labels: Feat, Design

#54 배포환경 작동 테스트
  src/common/comment/Comment.tsx
  src/common/editor/Editor.tsx
  src/common/header/HeaderInfo.tsx
  src/common/header/HeaderInfoLogged.tsx
  src/common/modal/ModalConfirm.tsx
  src/common/modal/ModalDetail.tsx
  src/common/modal/ModalEditor.tsx
  src/common/modal/ModalRegister.tsx
  src/common/topic/Topic.tsx
  src/pages/HomePage.tsx
  vite.config.ts
Labels: Test

#56 경험치 시스템 추가
  src/api/account.ts
  src/api/axios.ts
  src/common/editor/Editor.tsx
  src/common/header/Header.tsx
  src/common/header/HeaderInfoLogged.tsx
  src/common/info/InfoMyPageRight.tsx
  src/common/modal/ModalEditor.tsx
  src/common/modal/ModalRegister.tsx
  src/common/trending/TrendingComment.tsx
  src/config/const.tsx
  src/config/store.tsx
  src/config/types.ts
  src/pages/HomePage.tsx
  src/util/experience.ts
  vite.config.ts
Labels: Feat

#57 경험치 시스템 배포환경 테스트
  src/api/axios.ts
  vite.config.ts
Labels: Test

#58 경험치 시스템 추가
  src/util/experience.ts
Labels: Fix

#59 코멘트 컴포넌트 수정
  src/common/comment/CommentDetail.tsx
  src/common/modal/ModalDetail.tsx
  src/common/topic/TopicDrop.tsx
  src/config/types.ts
  src/pages/HomePage.tsx
  src/pages/RegisterPage.tsx
Labels: Feat, Fix, Design

#60 알림 기능 use-query 로 수정, 반응형 추가 수정사항 반영, 배포 테스트
  src/common/comment/CommentDetail.tsx
  src/common/header/HeaderInfoLogged.tsx
  src/common/modal/ModalDetail.tsx
  src/common/topic/TopicDrop.tsx
  src/config/const.tsx
  src/config/types.ts
  src/pages/HomePage.tsx
  src/pages/RegisterPage.tsx
Labels: Test

#61 console.log 디버깅 제거
  index.html
  src/common/modal/ModalDetail.tsx
  src/common/modal/ModalReport.tsx
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
  src/pages/RegisterPage.tsx
  src/pages/TagPage.tsx
  src/util/experience.ts
Labels: Remove

#62 디테일 모달 작업
  src/common/comment/CommentDetail.tsx
  src/common/modal/ModalDetail.tsx
Labels: Design

#63 디테일 모달 css 수정
  src/common/comment/CommentDetail.tsx
  src/common/header/HeaderInfo.tsx
  src/common/modal/ModalDetail.tsx
Labels: Design

#64 비밀번호 찾기 기능 구현 배포 환경 확인
  index.html
  package-lock.json
  package.json
  public/img/og.png
  src/App.tsx
  src/api/auth.ts
  src/common/comment/CommentDetail.tsx
  src/common/editor/Editor.tsx
  src/common/header/HeaderInfo.tsx
  src/common/modal/ModalDetail.tsx
  src/config/store.tsx
  src/config/types.ts
  src/pages/ErrorPage.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/PasswordFindPage.tsx
  src/pages/PasswordResetPage.tsx
  src/pages/RegisterPage.tsx
  src/pages/TagPage.tsx
  src/pages/WelcomePage.tsx
  tailwind.config.js
Labels: Feat, Test

#65 비밀번호 찾기 기능 구현
  src/pages/RegisterPage.tsx
Labels: Test

#66 최종 배포 테스트
  package-lock.json
  package.json
  src/common/editor/Editor.tsx
  src/common/editor/EditorToolbar.tsx
  src/doc/ERD.png
  src/doc/admin_page.png
  src/doc/architecture.png
  src/doc/editor_modal.png
  src/doc/main_image.png
  src/doc/main_page.png
  src/doc/my_page.png
  src/doc/register_page.png
  src/pages/PasswordResetPage.tsx
  src/pages/RegisterPage.tsx
Labels: Test

#67 다크모드 추가
  README.md
  src/common/header/Header.tsx
  src/common/profile/ProfileStatus.tsx
  src/common/trending/TrendingComment.tsx
  src/common/trending/TrendingContent.tsx
  src/config/ModalPortal.tsx
  src/hooks/useDarkmode.tsx
  src/pages/AdminPage.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
  src/pages/PasswordFindPage.tsx
  src/pages/RegisterPage.tsx
  src/pages/TagPage.tsx
  tailwind.config.js
  vite.config.ts
Labels: Feat

#68 최종 배포안 테스트
  src/App.tsx
  src/admin/modal/ModalReportCommentDetail.tsx
  src/admin/modal/ModalReportDetail.tsx
  src/common/comment/CommentDetail.tsx
  src/common/header/Header.tsx
  src/common/info/InfoMyPageRight.tsx
  src/common/modal/ModalDetail.tsx
  src/common/modal/ModalPicture.tsx
  src/common/modal/ModalReport.tsx
  src/common/profile/ProfileStatus.tsx
  src/common/toast/Toast.tsx
  src/common/trending/TrendingComment.tsx
  src/common/trending/TrendingContent.tsx
  src/config/store.tsx
  src/hooks/useDarkmode.tsx
  src/pages/AdminPage.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/MyPage.tsx
  src/pages/PasswordFindPage.tsx
  src/pages/RegisterPage.tsx
  src/pages/TagPage.tsx
  tailwind.config.js
Labels: Test

#70 Revert: 기존 다크모드 테마 CONFLICT 문제로 커밋 이전, 재배포
  src/pages/TagPage.tsx
Labels: Test

#71 Refactor : DarkMode 컬러 수정 및 Font-Size 수정
  src/api/axios.ts
  src/common/content/Content.tsx
  src/common/content/ContentFooter.tsx
  src/common/header/Header.tsx
  src/common/info/InfoMyPageLeft.tsx
  src/common/info/InfoMyPageRight.tsx
  src/common/topic/Topic.tsx
  src/common/topic/TopicDrop.tsx
  src/common/trending/TrendingComment.tsx
  src/common/trending/TrendingContent.tsx
  src/global.css
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/PasswordFindPage.tsx
  src/pages/RegisterPage.tsx
Labels: Refactor

#73 Design: 레벨 타이틀 다른 유저 마이페이지에서도 보이도록
  src/common/info/InfoMyPageRight.tsx
Labels: Design
